FROM alpine/git
WORKDIR /app
RUN git clone git@github.com:openshift-dedicated-lab01/covid-19-poc.git

FROM maven:3.5-jdk-8-alpine
WORKDIR /app/rest
COPY --from=develop /app/covid-19-poc/rest /app/rest
RUN mvn install
